### ISSUE TITLE
Implement Template mock

### ISSUE THREAD

**Issue by vysinsky** [vysinsky/sfcc-playground#22]
> 500 Error calling the route.
TypeError: Cannot read properties of undefined (reading 'text')
    at getDiscountsHtml (/Users/vysinm01/code/sfcc-playground/sfra/cartridges/app_storefront_base/cartridge/models/totals.js:120:36)
    at new totals (/Users/vysinm01/code/sfcc-playground/sfra/cartridges/app_storefront_base/cartridge/models/totals.js:143:30)
    at new CartModel (/Users/vysinm01/code/sfcc-playground/sfra/cartridges/app_storefront_base/cartridge/models/cart.js:97:27)
    at Array.<anonymous> (/Users/vysinm01/code/sfcc-playground/sfra/cartridges/app_storefront_base/cartridge/controllers/Cart.js:203:27)
    at next (/Users/vysinm01/code/sfcc-playground/server/src/server/Route.js:36:26)
    at Array.generateToken (/Users/vysinm01/code/sfcc-playground/sfra/cartridges/app_storefront_base/cartridge/scripts/middleware/csrf.js:60:5)
    at next (/Users/vysinm01/code/sfcc-playground/server/src/server/Route.js:36:26)
    at Object.generateToken (/Users/vysinm01/code/sfcc-playground/sfra/cartridges/app_storefront_base/cartridge/scripts/middleware/csrf.js:60:5)
    at Array.consent (/Users/vysinm01/code/sfcc-playground/sfra/cartridges/app_storefront_base/cartridge/scripts/middleware/consentTracking.js:33:24)
    at next (/Users/vysinm01/code/sfcc-playground/server/src/server/Route.js:36:26)

**Comment by vysinsky** [comment]
It could just load the template file and return the contents (without actual rendering).

**Comment by vysinsky** [comment]
even more simplified to just return a template name for now
